// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfoygM5SfepFIxMHji_oZqUi9s5Aik_Tg',
    appId: '1:594145925214:web:d5135baf325fd0d2b2fccf',
    messagingSenderId: '594145925214',
    projectId: 'cmsc23-jbbonza1',
    authDomain: 'cmsc23-jbbonza1.firebaseapp.com',
    storageBucket: 'cmsc23-jbbonza1.appspot.com',
    measurementId: 'G-0B3N7C5MDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABWPK52S5LmXH306oJatcCzJPynk0wP2s',
    appId: '1:594145925214:android:50bdc87e1a3839f1b2fccf',
    messagingSenderId: '594145925214',
    projectId: 'cmsc23-jbbonza1',
    storageBucket: 'cmsc23-jbbonza1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH_mb6Rwz44EonNXiU-DuSqRne4u0nf5A',
    appId: '1:594145925214:ios:23a3345d50820bc8b2fccf',
    messagingSenderId: '594145925214',
    projectId: 'cmsc23-jbbonza1',
    storageBucket: 'cmsc23-jbbonza1.appspot.com',
    iosClientId: '594145925214-7f1jqn8pkda1o33gc1gomk3rvs50ihil.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH_mb6Rwz44EonNXiU-DuSqRne4u0nf5A',
    appId: '1:594145925214:ios:23a3345d50820bc8b2fccf',
    messagingSenderId: '594145925214',
    projectId: 'cmsc23-jbbonza1',
    storageBucket: 'cmsc23-jbbonza1.appspot.com',
    iosClientId: '594145925214-7f1jqn8pkda1o33gc1gomk3rvs50ihil.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
